name: Example Nix Workflow

on:

  push:
    branches:
    - develop
    - stable
    - 'feature/**'

    paths:
    - '**.nix'
    - '**.hs'
    - '**.cabal'

  pull_request:
    branches:
    - develop
    - stable

    paths:
    - '**.nix'

  workflow_dispatch:

jobs:
  build:
    name: Example Nix Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
   
    - name: Preconfigure Cache
      run: |
        cat > /etc/nix/nix.conf << EOF
        trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
        substituters = https://hydra.iohk.io
        EOF

    - name: Install Cachix
      uses: cachix/cachix-action@v8
      with:
        name: ${{ secrets.CACHIX_CACHE_NAME }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Build Package
      run: nix-build scaffolding.nix -A haskell-project-boilerplate.all
