name: Example Nix Workflow

on:

  push:
    branches:
    - develop
    - stable
    - 'feature/**'

    paths-ignore:
    - '**.md'

  pull_request:
    branches:
    - develop
    - stable
    - 'feature/**'

    paths-ignore:
    - '**.md'

  workflow_dispatch:

jobs:
  build:
    name: Example Nix Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install Cachix
      uses: cachix/cachix-action@v8
      with:
        name: ${{ secrets.CACHIX_CACHE_NAME }}
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Configure Extra Cache
      id: extra
      run: |
        sed -E "s/(substituters = .*$)/\1 https:\/\/hydra.iohk.io/g" ~/.config/nix/nix.conf > ~/.config/nix/nix.conf
        sed -E "s/(trusted-public-keys = .*$)/\1 hydra.iohk.io:f\/Ea+s+dFdN+3Y\/G+FDgSq+a5NEWhJGzdjvKNGv0\/EQ=/g" ~/.config/nix/nix.conf > ~/.config/nix/nix.conf

    - name: Debug
      run: echo $(cat ~/.config/nix/nix.conf)

    - name: Build Package
      run: nix-build scaffolding.nix -A haskell-project-boilerplate.all
